# Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b = np.matrix([[0,11,12],[13,14,15],[16,17,18]])
sum = a + b
print(sum)


[[ 1 13 15]
 [17 19 21]
 [23 25 27]]


# Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b = np.matrix([[0,11,12],[13,14,15],[16,17,18]])
multiply = a * b
print(multiply)


[[ 74  90  96]
 [161 216 231]
 [248 342 366]]


# Write a Python Program to Transpose a Matrix?

In [16]:
import numpy as np
mat = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
transpose = mat.T
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Write a Python Program to Sort Words in Alphabetic Order?

In [22]:
def sort_string(str):
    return "".join(sorted(str))


In [23]:
sort_string('zyx')

'xyz'

# Write a Python Program to Remove Punctuation From a String?

In [81]:
def rem_punc(a):
    punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    for i in a:
        if i in punc:
            corrected_str = a.replace(i ,'')
            a = corrected_str
    print(corrected_str)

In [84]:
rem_punc("Today's a fine % day$")

Todays a fine  day
